--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-11-10 16:40:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4933 (class 1262 OID 58451)
-- Name: aep2; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE aep2 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'pt-BR';


ALTER DATABASE aep2 OWNER TO postgres;

\connect aep2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 66295)
-- Name: administrador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administrador (
    administrador_id bigint NOT NULL,
    nome character varying(255)
);


ALTER TABLE public.administrador OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 66294)
-- Name: administrador_administrador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.administrador ALTER COLUMN administrador_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administrador_administrador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 66301)
-- Name: aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aluno (
    aluno_id bigint NOT NULL,
    ra character varying(255),
    nome character varying(255)
);


ALTER TABLE public.aluno OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 66300)
-- Name: aluno_aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aluno ALTER COLUMN aluno_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 58453)
-- Name: disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplina (
    disciplina_id bigint NOT NULL,
    nome character varying(255),
    professor character varying(255)
);


ALTER TABLE public.disciplina OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 58452)
-- Name: disciplina_disciplina_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disciplina ALTER COLUMN disciplina_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplina_disciplina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 58461)
-- Name: material; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.material (
    material_id bigint NOT NULL,
    descricao character varying(255),
    tipo character varying(255),
    titulo character varying(255),
    url character varying(255),
    disciplina_id bigint
);


ALTER TABLE public.material OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 58460)
-- Name: material_material_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.material ALTER COLUMN material_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 66309)
-- Name: professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professor (
    professor_id bigint NOT NULL,
    ra character varying(255),
    nome character varying(255)
);


ALTER TABLE public.professor OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 66308)
-- Name: professor_professor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.professor ALTER COLUMN professor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_professor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4923 (class 0 OID 66295)
-- Dependencies: 222
-- Data for Name: administrador; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.administrador VALUES (1, 'teste');
INSERT INTO public.administrador VALUES (2, 'Ryu The Runner');


--
-- TOC entry 4925 (class 0 OID 66301)
-- Dependencies: 224
-- Data for Name: aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.aluno VALUES (1, NULL, 'Erick Grisoste');
INSERT INTO public.aluno VALUES (3, NULL, 'Ryu The Runner');


--
-- TOC entry 4919 (class 0 OID 58453)
-- Dependencies: 218
-- Data for Name: disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.disciplina VALUES (1, 'Programação Orientada a Objetos', 'Carlos Henrique');
INSERT INTO public.disciplina VALUES (7, 'Teste', 'Teste');


--
-- TOC entry 4921 (class 0 OID 58461)
-- Dependencies: 220
-- Data for Name: material; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.material VALUES (4, 'Material de apoio da aula introdutória sobre classes, objetos e encapsulamento.', 'Vídeo', 'Introdução ao Conceito de Classes e Objetos', 'https://www.youtube.com/watch?v=xvFZjo5PgG0', 1);
INSERT INTO public.material VALUES (24, 'teste', 'Vídeo', 'teste', 'https://www.youtube.com/watch?v=xvFZjo5PgG0', 7);


--
-- TOC entry 4927 (class 0 OID 66309)
-- Dependencies: 226
-- Data for Name: professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.professor VALUES (1, NULL, 'Marcos Souza');
INSERT INTO public.professor VALUES (2, NULL, 'Ryu The Runner');


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 221
-- Name: administrador_administrador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.administrador_administrador_id_seq', 2, true);


--
-- TOC entry 4935 (class 0 OID 0)
-- Dependencies: 223
-- Name: aluno_aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aluno_aluno_id_seq', 3, true);


--
-- TOC entry 4936 (class 0 OID 0)
-- Dependencies: 217
-- Name: disciplina_disciplina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplina_disciplina_id_seq', 7, true);


--
-- TOC entry 4937 (class 0 OID 0)
-- Dependencies: 219
-- Name: material_material_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.material_material_id_seq', 24, true);


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 225
-- Name: professor_professor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professor_professor_id_seq', 2, true);


--
-- TOC entry 4767 (class 2606 OID 66299)
-- Name: administrador administrador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT administrador_pkey PRIMARY KEY (administrador_id);


--
-- TOC entry 4769 (class 2606 OID 66307)
-- Name: aluno aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (aluno_id);


--
-- TOC entry 4763 (class 2606 OID 58459)
-- Name: disciplina disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_pkey PRIMARY KEY (disciplina_id);


--
-- TOC entry 4765 (class 2606 OID 58467)
-- Name: material material_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_pkey PRIMARY KEY (material_id);


--
-- TOC entry 4771 (class 2606 OID 66315)
-- Name: professor professor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (professor_id);


--
-- TOC entry 4772 (class 2606 OID 58468)
-- Name: material fk8tdscq8v4qrgiwgq3lgnrmagk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT fk8tdscq8v4qrgiwgq3lgnrmagk FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(disciplina_id);


-- Completed on 2025-11-10 16:40:57

--
-- PostgreSQL database dump complete
--

